builds:
  - goarch:
      - arm
    goarm:
      - 6
archive:
  wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: true